#define MSGCOUNT 10

int MetroidPickupMessages[PICKUPTYPES][MSGCOUNT] =
{
    {
        "SUPER MISSILE TANK: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "MISSILE TANK: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "POWER BOMB TANK: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "ENERGY TANK: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "SPEED BOOSTER: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "SPACE JUMP: ACQUIRED",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
    },
    {
        "SPAZER BEAM: ACQUIRED",
        "Add a Z to the name and it becomes 50% cooler. Who knew?",
        "Yeah I ain't feeling all that spazed.",
        "Insert quantum-physics-related joke here.",
        "Have your SSG already.",
        "But sour Skittles are \canaaaaaaaasty",
        "\caEAT YOUR GLOWING PLASMA VEGETABLES.",
        "",
        "",
        "",
    },
    {
        "PLASMA BEAM: ACQUIRED",
        "Obviously this isn't based off Metroid Prime; this doesn't instagib everything.",
        "At least you can see the shot disappearing.",
        "Aren't all the beams technically plasma, though?",
        "Also useful for making hot chocolate.",
        "But I wanted a flamethrower :(",
        "Something something high definitions TVs something used this joke already.",
        "When do we get the LCD Beam?",
        "",
        "",
    },
    {
        "WAVE BEAM: ACQUIRED",
        "Ride it.",
        "Gnarly, dude.",
        "I was kinda hoping it shot curly fries.",
        "It's purple due to the Doppler effect distorting the light so that ahaha no.",
        "ITT: apparently waves explode into shrapnel.",
        "Dammit, stop shooting it at your TV! It doesn't do that!",
        "You wanted a sniping weapon for your chaingun replacement? That's stupid.",
        "YOU! One more step and it'll be your last!",  // TK Baha
        "Well, it's only polite.",
    },
    {
        "ICE BEAM: ACQUIRED",
        "No puns, please. It'd set a chilling precedent.",
        "Keeps your beer cold or your money back.",
        "Thermodynamics is confused.",
        "Also freezes gravity.",
        "How do I set it to slush mode again?",
        "A perfect complement to your cold, cold heart.",
        "Great for arguments, too.",  // *heated* arguments
        "Hey, don't lose your cool now.",
        "When Hell freezes over? Is that a challenge?",
    },
    {
        "LONG BEAM: ACQUIRED",
        "BONG LEAM: ACQUIRED",
        "Shouldn't this be the first beam you get?",
        "After years of murdering Space Pirates, Samus finally realizes her dream of having a giant metal penis on her arm.",
        "Cherish their expressions as they realize that you're killing them with a giant white shaft.",
        "This would go perfectly with the Firemace.",
        "Go on, drop 'em with your white rod.",
        "The missile combo is only as satisfying as you want it to be.",
        "Honestly, who needs maturity anyway?",
        "420 energy blaze it pirates",
    },
    {
        "BEAM CONVERSION UNIT: ACQUIRED",
        "As you switch to the Wave Beam, Ridley gets scared. He remembers.",
        "Took freakin' long enough to jailbreak the thing.",
        "In the time it takes to charge, you coulda just shot the guy a bunch more times.",
        "But can it shock combo?",
        "No Phazon Beam for you.",
        "And just how did this end up in Hell, anyway?",
        "why does a energy-based weapon converter sound like a break-action shotgun do you even respect metroid you should be banned from making mods ever again kill yourself 4ever",
        "Seriously Samus, would it kill you to back up your upgrades now and then?",
        "But I can't even shoot black holes.",
    },
    {
        "\cjdX000FFFsF \cferror",
        "Dev-tested, IDL-approved.",
        "What's next, a minigun?",
        "Hey uh Samus you might wanna look into that heartbeat thing. That's not healthy.",
        "Oh my god this mod rips off Doom so much.",
        "What's the cost of rent for souls, anyway?",
        "Make the demons your bitch.",
        "So when you use the combo... what happens to your hand?",
        "Status on the return of Samus: not returned.",
        "Ah, yes, the revered \"I'M GONNA CHOP YOU IN HALF\" argument. A classic.",
    },
    {
        "CHROMA STORM: ACQUIRED",
        "You want a Hyper Beam? Fine.",
        "Blast those demons with the power of FABULOUS.",
        "We have a very loose interpretation of gold. And pots.",
        "In which a bored scientist took a prism and decided, \"We need to weaponize this.\"",
        "Ever decided to murder demons and repaint the area at the same time? Well now you can!",
        "Next up, the Fruit Salad Blaster.",
        "You enjoy penetrating them with your beams. Admit it.",
        "It's... it's all over everything...",
        "omg homo gun",
    },
};
